// auth
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"


export const LOGOUT_REQUEST = "LOGOUT"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"

// all users
export const ALL_USER_REQUEST = "ALL_USER_REQUEST"
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"
export const ALL_USER_FAILURE = "ALL_USER_FAILURE"

// personal user or profile for whole application
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE"

// personal profile for specific profile page of app
export const PROFILE_REQUEST = "PROFILE_REQUEST"
export const PROFILE_SUCCESS = "PROFILE_SUCCESS"
export const PROFILE_FAILURE = "PROFILE_FAILURE"

// other user or profile/account
export const LOAD_USER_ACCOUNT_REQUEST = "LOAD_USER_ACCOUNT_REQUEST"
export const LOAD_USER_ACCOUNT_SUCCESS = "LOAD_USER_ACCOUNT_SUCCESS"
export const LOAD_USER_ACCOUNT_FAILURE = "LOAD_USER_ACCOUNT_FAILURE"

// update profile
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE"

// change password
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE"

// forgot password
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"

// reset password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE"

// delete user
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE"

// search user
export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST"
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"
export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE"

// follow or unfollow user
export const FOLLOW_OR_UNFOLLOW_USER_REQUEST = "FOLLOW_OR_UNFOLLOW_USER_REQUEST"
export const FOLLOW_OR_UNFOLLOW_USER_SUCCESS = "FOLLOW_OR_UNFOLLOW_USER_SUCCESS"
export const FOLLOW_OR_UNFOLLOW_USER_FAILURE = "FOLLOW_OR_UNFOLLOW_USER_FAILURE"

// post
export const GET_POST_REQUEST = "GET_POST_REQUEST"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILURE = "GET_POST_FAILURE"

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST"
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS"
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE"

export const COMMENT_REQUEST = "COMMENT_REQUEST"
export const COMMENT_SUCCESS = "COMMENT_SUCCESS"
export const COMMENT_FAILURE = "COMMENT_FAILURE"

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE"

// get my posts
export const GET_MY_POST_REQUEST = "GET_MY_POST_REQUEST"
export const GET_MY_POST_SUCCESS = "GET_MY_POST_SUCCESS"
export const GET_MY_POST_FAILURE = "GET_MY_POST_FAILURE"

// get user's posts
export const GET_USER_POST_REQUEST = "GET_USER_POST_REQUEST"
export const GET_USER_POST_SUCCESS = "GET_USER_POST_SUCCESS"
export const GET_USER_POST_FAILURE = "GET_USER_POST_FAILURE"

export const ADD_NEW_POST_REQUEST = "ADD_NEW_POST_REQUEST"
export const ADD_NEW_POST_SUCCESS = "ADD_NEW_POST_SUCCESS"
export const ADD_NEW_POST_FAILURE = "ADD_NEW_POST_FAILURE"

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE"

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST"
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS"
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE"